[package]
name = "micro-kira-loaders"
version = "0.1.0"
edition = "2024"

[dependencies]
kira = { version = "0.12.0", default-features = false, features = [
	"symphonia",
] }
micro = { path = "../micro" }
micro-asset = { path = "../micro-asset" }
